#
# Play:: Index
#
# Copyright 2023 Andrew Jones
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
  - import_playbook: backports.yml
  - import_playbook: x11.yml
  - import_playbook: kde.yml

  - name: Index
    hosts: all
    tasks:
      - name: Install misc packages
        ansible.builtin.apt:
          update_cache: yes
          cache_valid_time: 300
          state: latest
          name:
            - curl
            - git
            - ansible
            - cups
            - cups-bsd
            - cups-client
            - cups-filters
            - imagemagick
            - iw # replaces iwconfig, new kernel driver
            - keepassx
            - libimage-exiftool-perl # exiftool
            - libjpeg-turbo-progs # jpegtran
            - lsb-release # ansible relies on this for facts
            - maven
            - mpv
            - net-tools # netstat
            - nvi # vi, non-vim
            - vim-motif
            - openjdk-25-jdk
            - openssh-client
            - openssh-server
            - pavucontrol
            - python3
            - python3-pip
            - rsync
            - ruby-dev
            - ruby
            - silversearcher-ag
            - unison

      - name: Remove default editors
        ansible.builtin.apt:
          state: absent
          purge: true
          name:
            - vim-tiny
            - vim-common
            - nano
            
      - name: Detect battery
        shell: "/bin/lshw -c power"
        ignore_errors: true
        register: lshw_power
            
  - import_playbook: laptop.yml
    when: lshw_power.stdout.find('power') != -1

  - import_playbook: pcspkr.yml
  - import_playbook: signal.yml
  - import_playbook: spotify.yml
  - import_playbook: steam.yml
  - import_playbook: wine.yml
  - import_playbook: yubico_authenticator.yml
